### ISSUE TITLE
example

### ISSUE THREAD

**Issue by badrazizi** [carlosmarti/GodotAppodeal#1]
@carlosmarti could you add usage example

**Comment by carlosmarti** [comment]
Sure, I'll find some time tomorrow to get that in.

**Comment by Shin-NiL** [comment]
+1 vote for an example here ;)

EDIT1:
I'm trying to build godot with GodotAppodeal module. So far I need to update config.py to find android/sdk/applovin-6.1.4.jar file. But I'm getting the following error running ant building:

```
-compile:
    [javac] Compiling 4 source files to /home/shinnil/dev/godot/platform/android/java/bin/classes
    [javac] /home/shinnil/dev/godot/platform/android/java/src/com/android/godot/GodotAppodeal.java:48: initialize(android.app.Activity,java.lang.String,int) in com.appodeal.ads.Appodeal cannot be applied to (android.app.Activity,java.lang.String)
    [javac]                     Appodeal.initialize(activity, appKey);
    [javac]                             ^
    [javac] 1 error

BUILD FAILED
/home/shinnil/dev/android-sdk-linux/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/shinnil/dev/android-sdk-linux/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.
```

Any tips there?
Thanks!

EDIT2:
It was missing an argument on GodotAppodeal.java, line 48:

``` java
                    Appodeal.initialize(activity, appKey);
```

**Comment by badrazizi** [comment]
true 
just compiled it and got the same error missing an argument

**Comment by carlosmarti** [comment]
I just added the example. I will look into that and will update the repository as soon as possible. That error has to be because of appodeal new library. I will check on how they changed the test.

EDIT
@Shin-NiL I have updated the code to fix this issue make sure you get the new repo.

**Comment by Shin-NiL** [comment]
@carlosmarti Thanks!
