### ISSUE TITLE
Reward Video Finished Callback Not Working

### ISSUE THREAD

**Issue by QuadTeleport** [carlosmarti/GodotAppodeal#17]
The reward video finished callback is not working

**Comment by Shin-NiL** [comment]
I am unable to compile and test right now, but the issue seems to be on appodeal/android/src/GodotAppodeal.java line 423:

`runCallback(String.format("onRewardedVideoFinished. Reward: %d %s", amount, name));`

it should be something like:

`runCallback("onRewardedVideoFinished");`

right?
