### ISSUE TITLE
Google Warning: MoPub security issues

### ISSUE THREAD

**Issue by rofetsch** [carlosmarti/GodotAppodeal#6]
Hello Carlos,

I love your work, it really makes adding ad support easy.

I'm getting warnings for my Android app saying the currently used MoPub version has some security issues.

Any idea how to fixed that?

My best guess is to replace one of the included Jar-Files with a newer version, however I don't know which.

**Comment by carlosmarti** [comment]
Yeah there is a new sdk out for Appodeal and that should take care of that issue. I will update this later on today.

**Comment by carlosmarti** [comment]
I have updated all of the libs for Appodeal including the new unity video ads. If you can update and build to test that everything is in order and let me know would be great. I have a game development meet up to get to and have not tested to make sure that it builds.

**Comment by rofetsch** [comment]
Perfect, thanks a lot!
