### ISSUE TITLE
Dependency not found: com.google.android.gms:play-services-ads:+

### ISSUE THREAD

**Issue by rofetsch** [carlosmarti/GodotAppodeal#7]
Hi there,

my Gradle-Build fails, because it can not find the required Play Service version:

`Parallel execution with configuration on demand is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest
:processDebugResources
 Position 225:28-65 : No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

:processDebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processDebugResources'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/Android/sdk/build-tools/19.1.0/aapt'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.638 secs
`

I tried hard (but failed) to find a jar that matches the following dependency (from build.gradle): 
com.google.android.gms:play-services-ads:+

Is the current version of the Play Service not suppoted by the module?

**Comment by Shin-NiL** [comment]
You can try to install _Google Play Services_ on the _Extras_ tabs from Android SDK Manager.  Downloading _Android Support Repository_, _Android Support Library_ and _Google Repository_ should be a good idea too :P

**Comment by rofetsch** [comment]
Thanks a lot!

That solved the problem.
